//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class rentcar4Entities2 : DbContext
    {
        public rentcar4Entities2()
            : base("name=rentcar4Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clasevehiculo> Clasevehiculo { get; set; }
        public virtual DbSet<contrato> contrato { get; set; }
        public virtual DbSet<contratohistory> contratohistory { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<NFC> NFC { get; set; }
        public virtual DbSet<Referido> Referido { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    
        public virtual int calculardiasextras()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("calculardiasextras");
        }
    
        public virtual int cerrarcontratos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("cerrarcontratos");
        }
    }
}
